### ISSUE TITLE
Pip install on Centos requires Pywin32

### ISSUE THREAD

**Issue by josthoma** [robotframework/RIDE#1874]
Hi Team,
Pip install on a Centos Machine is trying to find a Pywin32 even though the requirements.txt states Pywin check only for windows OS

**Comment by tonynii** [comment]
MAC also have this issue

**Comment by HelioGuilherme66** [comment]
You can try to install current development version with:
```
sudo -H pip install -U https://github.com/robotframework/RIDE/archive/master.zip
```

**Comment by williamhatch** [comment]
in mac, env:
/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py:16633: UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/robotide/__init__.py", line 83, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "/usr/local/lib/python2.7/site-packages/robotide/__init__.py", line 102, in _run
    from robotide.application import RIDE
  File "/usr/local/lib/python2.7/site-packages/robotide/application/__init__.py", line 16, in <module>
    from .application import RIDE, Project
  File "/usr/local/lib/python2.7/site-packages/robotide/application/application.py", line 22, in <module>
    from robotide.namespace import Namespace
  File "/usr/local/lib/python2.7/site-packages/robotide/namespace/__init__.py", line 16, in <module>
    from .namespace import Namespace
  File "/usr/local/lib/python2.7/site-packages/robotide/namespace/namespace.py", line 31, in <module>
    from robotide.publish import PUBLISHER, RideSettingsChanged, RideLogMessage
  File "/usr/local/lib/python2.7/site-packages/robotide/publish/__init__.py", line 123, in <module>
    from .messages import *
  File "/usr/local/lib/python2.7/site-packages/robotide/publish/messages.py", line 21, in <module>
    from .messages2 import *
  File "/usr/local/lib/python2.7/site-packages/robotide/publish/messages2.py", line 24, in <module>
    from robotide.publish import publisher
  File "/usr/local/lib/python2.7/site-packages/robotide/publish/publisher.py", line 24, in <module>
    from pubsub import pub
ImportError: cannot import name pub

and I did pip install pub

**Comment by HelioGuilherme66** [comment]
@williamhatch That is not the same problem as original poster. (your is solved by `sudo -H pip install pypubsub==3.3.0`

**Comment by williamhatch** [comment]
@HelioGuilherme66 many thanks!

**Comment by agschaid** [comment]
Hi, 

When building Plone 5.2rc5 with buildout this problem still persists. Is there any timeline when this will be fixed? I am a bit reluctant to installing dev versions on my production environment ;)

**Comment by agschaid** [comment]
Looks better with 1.7.4a1
