### ISSUE TITLE
RIDE 1.7.4b2 arguments are ignored

### ISSUE THREAD

**Issue by povar81** [robotframework/RIDE#2029]
I run test via custom script in execution profile:
the script is a cmd file which takes arguments sent to it from ride:
%RF_ARGS%
and uses them to run specific case:
call "%PYTHONPATH%\Scripts\robot.exe"  --loglevel TRACE -C off -d %RF_RUNNER_HOME%\out -l NONE -r NONE  --variable RESOURCE_FILE:%TEST%\suits\resources\local\Mdr_Resources_local_41.txt %RF_ARGS%

same script works on 1.7.4b1 as usual:
I write 
-i testname1   
in Arguments and only that specific test is run (or multiple tests with the same tag)

but in version 1.7.4b2 it works weird:
only the first time it works properly, but then no matter what tag (testname) I write in Arguments:
-i testname2
-i testname3 etc.
it still runs only the first run testname1.

**Comment by plumbum-se** [comment]
I have the same issue with 1.7.4b2. Example:
Arguments: [-v DUT_VERSION:2.7.4]
...but this gives
command: robot -v DUT_VERSION:2.7.3
The only workaround I've found is to restart Ride.

**Comment by HelioGuilherme66** [comment]
@povar81 and @plumbum-se  Can you please test with current development version?
I could not reproduce with current development version (on Windows 7 with Python 3.7):
```
pip install -U https://github.com/robotframework/RIDE/archive/master.zip
```

**Comment by povar81** [comment]
No, it doesn't get reproduced on version RIDE 1.7.4rc1.dev  (Windows 7 on Python 3.7.4).
It works correctly, argument is taken into account everytime.
Also, does this version support old style FOR loops?

**Comment by HelioGuilherme66** [comment]
@povar81 I have not tested if supports the old style FOR loops.
You can test in a copy of your old style test, by using *ONLY* the Editor (Grid/Cell Editor) and not the Text Editor. Do some changes and save the file, then close RIDE and reopen the file. If it works, then disable the Text Editor in Plugin Manager.
Good Luck.

**Comment by plumbum-se** [comment]
I agree with povar81, it now works fine.

**Comment by povar81** [comment]
Thank you, it seems to support old FOR loops, plus colorization bug, and crashing bug don't get reproduced, so it's a perferct version for us, thank you :)

**Comment by povar81** [comment]
Now the only remaining problem is the cursor position)

**Comment by HelioGuilherme66** [comment]
> Now the only remaining problem is the cursor position)

@povar81 What do you mean? If you are using Text Editor (and loose the old FOR style), the cursor position is fixed!

**Comment by povar81** [comment]
It's partially fixed. Let's continue discussion in the thread
https://github.com/robotframework/RIDE/issues/1944

**Comment by povar81** [comment]
@HelioGuilherme66, unfortunately it does change the FOR loops. Can I disable this feature somehow?

**Comment by HelioGuilherme66** [comment]
@povar81 I suppose the only way to disable that, is to disable the Text Editor in manage plugins.
Do you use an old version of robot framework?

**Comment by povar81** [comment]
@HelioGuilherme66, yes we use older version of robotframework==2.8.6.
Unfortunately, disabling the Text Editor doesn't help, it still gets formatted after any change and restart of RIDE.

**Comment by povar81** [comment]
Sorry, I meant that we use 2 versions of RIDE in our team:
robotframework==2.8.6 (with Python 2)
and
robotframework==3.1.2 (with Python 3)
and this loop syntax is the only major compatibility problem we face right now (apart from minor problems with execution speed and log size, but that we can live with)

**Comment by HelioGuilherme66** [comment]
Why not upgrade robotframework?

**Comment by povar81** [comment]
It's not that easy: 
1. We need to fix execution speed, log size, replace java(jython) keyword with python's analogues, stabilize it
2. We have customer's environment which we can't update whenever we want to, we have to pass certain bureacratic procedures, in the meantime we wanted to keep our cases compatible with both versions.

**Comment by HelioGuilherme66** [comment]
Seems that we have this regression. At least when using date/time stamps outputdir. For example, using this argument:
```
-d ./%date:~-4,4%%date:~-10,2%%date:~-7,2%-%time:~0,2%h%time:~3,2% 
```
Thanks to Slack user TonyS.
