### ISSUE TITLE
Grid does not resize and autocompletion does not work

### ISSUE THREAD

**Issue by rohansekhri** [robotframework/RIDE#2083]
I was setting up a new project on a new system. Here are the details:

Setup on Win10 (64-bit):

- Tried Python 3.6, 3.7 and 3.8
- RIDE 1.7.3.1 running on Python 3.6.7
- Installations were done using pip : pip install robotframework and pip install robotframework-ride. 

The following were installed themselves
```
numpy==1.17.4
Pillow==6.2.1
Pygments==2.5.2
PyPubSub==3.3.0
pywin32==227
robotframework==3.1.2
robotframework-ride==1.7.3.1
robotframeworklexer==1.1
six==1.13.0
wxPython==4.0.7.post2
```
The issues:

- Bug #1962 is still reproducible with the config above
- Typing ```Should be``` and pressing ```CTRL + Space``` does not work anymore

More Info, in case it helps:

```
C:\Python36\Scripts>python ride.py
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.IdleEvent'> returned a result with an error set
```

![image](https://user-images.githubusercontent.com/46380417/70581136-2cd4d480-1b84-11ea-88b3-175298fcfccf.png)

**Comment by rohansekhri** [comment]
I was setting up a new project on a new system. Here are the details:

**Setup**:

1. Tried Python 3.6, 3.7 and 3.8
2. RIDE 1.7.3.1 running on Python 3.6.7
3. Installations were done using pip : pip install robotframework and pip install robotframework-ride. The following were installed themselves

```
numpy==1.17.4
Pillow==6.2.1
Pygments==2.5.2
PyPubSub==3.3.0
pywin32==227
robotframework==3.1.2
robotframework-ride==1.7.3.1
robotframeworklexer==1.1
six==1.13.0
wxPython==4.0.7.post2
```
The issues: 

- Bug #1962 is still reproducible with the config above
Typing ```Should be``` and pressing CTRL + Space does not work anymore

![image](https://user-images.githubusercontent.com/46380417/70581106-1169c980-1b84-11ea-8c32-361a671a33d1.png)

**Comment by HelioGuilherme66** [comment]
@rohansekhri You should have noticed that the issues are fixed for version 1.7.4. The version you installed does not include the fixes. You can install the released 1.7.4b2 or the development version from `master` branch.

**Comment by rohansekhri** [comment]
@HelioGuilherme66 Tried 1.7.4b2, but still no luck. Both issues exist. Thanks

![image](https://user-images.githubusercontent.com/46380417/70628830-df457f80-1bf6-11ea-83b5-d836ba875e5a.png)

**Comment by Nyral** [comment]
> Bug #1962 is still reproducible with the config above
That's a PR, you probably mean #1798. That issue is fixed, as it can be seen in the image you posted above.

> Typing Should be and pressing CTRL + Space does not work anymore
In previous version it wasn't working because there was a conflict between that shortcut and Text Editor shortcuts. [This has also been fixed.](https://github.com/robotframework/RIDE/pull/2005)

Release 1.7.4b2 does not contain the fix for the second issue. You need to get latest development version (i.e. whatever is on master at this moment)

**Comment by rohansekhri** [comment]
> > Bug #1962 is still reproducible with the config above
> 
> That's a PR, you probably mean #1798. That issue is fixed, as it can be seen in the image you posted above. What's not clear? If you want columns to stop autosizing, then you need to go to `Tools > Preferences > Grid Editor` and uncheck `Auto size columns` option.
> 
> > Typing Should be and pressing CTRL + Space does not work anymore
> 
> In previous versions it wasn't working because there was a conflict between that shortcut and Text Editor shortcuts. [This has also been fixed.](https://github.com/robotframework/RIDE/pull/2005)
> 
> @rohansekhri @HelioGuilherme66 Release 1.7.4b2 does not contain the fix for the second issue. You need to get latest development version (i.e. whatever is on master at this moment).
