### ISSUE TITLE
Reload the wrong workspace

### ISSUE THREAD

**Issue by Gloria323** [robotframework/RIDE#2611]
Hi, 
  I encountered an error when using RIDE v2.0.7dev4. Here are the steps I followed:

> 1. Opened test suite suiteA in RIDE.
> 2. Edited the same test suite using vscode and saved it.
> 3. RIDE displayed a dialog box stating, "Workspace modifications detected on the file system. Do you want to reload the workspace?"
> 4. I selected "Yes."
> 5. The test suite was reloaded, but it loaded the previously opened suiteB instead of the currently open and edited suiteA.

Could you please assist me in resolving this issue? Thank you.

$ pip list
Package                         Version
------------------------------- ----------
async-generator                 1.10
attrs                           23.1.0
bcrypt                          4.0.1
certifi                         2023.5.7
cffi                            1.15.1
cryptography                    41.0.1
exceptiongroup                  1.1.1
h11                             0.14.0
idna                            3.4
lxml                            4.9.2
ncclient                        0.6.7
netconf-console                 2.3.3
netconf-console2                3.0.0
numpy                           1.25.0
outcome                         1.2.0
paramiko                        3.2.0
Pillow                          9.5.0
pip                             23.1.2
psutil                          5.9.5
pycparser                       2.21
Pygments                        2.15.1
PyNaCl                          1.5.0
Pypubsub                        4.0.3
pyreadline                      2.1
PySocks                         1.7.1
pywin32                         306
robotframework                  6.1
robotframework-archivelibrary   0.4.2
robotframework-ftplibrary       1.9
robotframework-pythonlibcore    4.1.2
robotframework-ride             2.0.7.dev4
robotframework-selenium2library 3.0.0
robotframework-seleniumlibrary  6.1.0
robotframework-sshlibrary       3.8.0
scp                             0.14.5
selenium                        4.10.0
setuptools                      65.5.0
six                             1.16.0
sniffio                         1.3.0
sortedcontainers                2.4.0
trio                            0.22.0
trio-websocket                  0.10.3
urllib3                         2.0.3
wsproto                         1.2.0
wxPython                        4.2.1

**Comment by axiom41** [comment]
I can confirm this happens to me as well (Windows 10/11, Python 3.7.9 and newer), even since the beginning of v2.0.x... Maybe it's related with handling of "default directory" and "recent files" entries in C:\Users\...\AppData\Roaming\RobotFramework\ride\settings.cfg file that is not updated correctly.
Also, the same dialog about reloading the workspace/project is shown even when opening it at the beginning of its loading in RIDE, so without any change, realistically

**Comment by Gloria323** [comment]
@axiom41 , thanks for your reminder!

**Comment by JFoederer** [comment]
Is there some more info available on when this happens? Is it 100% reproducible with any 2 test suites? Small or large? Or only when there are also (external) resources or libraries involved? Or...?

A smallest example would be helpful.

**Comment by Gloria323** [comment]
Hi @JFoederer , It's 100% reproduced on my computer(win11). My python version is 3.11.4.

**Comment by Gloria323** [comment]
I didn't encounter this issue with the 2.0b1 version of RIDE that I installed a few days ago. The problem started when I upgraded to the master and 2.0.6 versions.

**Comment by Gloria323** [comment]
I checked the C:\Users\...\AppData\Roaming\RobotFramework\ride\settings.cfg file mentioned by axiom41. 
The recent_files = **_suiteA, suiteB,_** suiteC.
Then edit suiteA, the RIDE dialog box appears. I clicked "Yes".
The recent_files changed to " _suiteB, suiteA_, suiteC".
In RIDE, the workspace reload suiteB.

**Comment by axiom41** [comment]
Hi @JFoederer
I recorded a short video showing what happens when opening different projects (see link at the end) and below there is the description of steps performed while recording it (my system is now Win 11 x64, Python 3.11.4, RIDE 2.0.7dev4, but, as i mentioned before, it's been a while).

I first launched RIDE (without any other "external" application) that opens with last workplace/project, in my example "NOREGR_GEST-SIT_T1", then i tried to open another workplace/project (NOREGR_GEST-SIT) using RIDE file manager, and dialog opens immediately after loading it (when obviously any file hasn't been modified).
I answer "No" and workplace is loaded and list of recent projects has been correctly updated (NOREGR_GEST-SIT is now the 1st and "initial" NOREGR_GEST-SIT_T1 is now at 2nd place).
Then i re-choose NOREGR_GEST-SIT_T1 from this list and everything's working fine
The i repeat the task selecting (still from the file manager) another workplace/project (NOREGR_GEST-COLL-QA) and dialog appears again (no files actually modified also now). I answer "No" again, project is loaded and list of recent projects is updated (NOREGR_GEST-COLL_QA at n. 1, NOREGR_GEST-SIT_T1 at n. 2 and NOREGR_GEST-SIT at n. 3)
I click again on 1st project in the list (NOREGR_GEST-COLL_QA) and project is loaded without any dialog.
Then i open another more project (NOREGR_GEST-COLL1) this time using the folder icon in the top bar. Dialog appears and i answer "Yes": "NOREGR_GEST-COLL1" is neither not loaded nor added to recent projects list and RIDE returns on the one that was already open, i.e. NOREGR_GEST-SIT_T1

I then repeated the steps with same projects after closing and reopening RIDE and no dialogs were shown UNTIL i selected another more project (not in the video).
I then suspect it's something related to some kind of "cache" that RIDE uses to decide if a project "needs" to be reoladed even on opening

You can view/download the video file [here](https://drive.google.com/file/d/1BxIHMbcyLsiSz7kgB5lcUqsZyUGh9tEh/view?usp=sharing)

**Comment by JFoederer** [comment]
> It's 100% reproduced on my computer(win11). My python version is 3.11.4.

I am surprised to hear you have a 100% fail rate. I have encountered this issue many times over the past period, but am so far unable to pinpoint the root cause, nor have I been able to construct a consistent reproduction scenario.

@Gloria323 , could you please check if it still reproduces on your system with this small example?

Create a set of folders named `suiteA`, `suiteB` ... `suiteE`. All with just a single `.robot` file. Mine is called `not_much.robot` which just contained
```
*** Test Cases ***
just one
    no operation
```

The 5 folders exceed the default file history limit by one. To include the hint from @axiom41 as well.

Now the interesting part... When I first switched to using this new set of folders (`open directory`), I immediately ran into the issue. This was however the only occurrence. With just this set of folders in the recent files, I have not been able to reproduce the issue. Not even when removing these folders from the recent files history and putting my old ones in.

I am very interested to learn how your system responds when using only these mini test suites.

**Comment by Gloria323** [comment]
Hi @JFoederer ,
    I believe the issue I encountered is different from @axiom41 's. My problem is that when I **_edit a file that is already open in RIDE_** using vscode, RIDE reloads the wrong file instead of the one I just edited. Please refer to the video "my_issue" for reference. 

In fact, I didn't experience the same problem as Robin, and I have also tried your suggestions. Please refer to the video "test.mp4" for further details. 

https://github.com/robotframework/RIDE/assets/121922008/c0639ae3-78b2-4c6f-b9e4-f915c5595962

https://github.com/robotframework/RIDE/assets/121922008/cb773ed8-32e0-444c-bcca-f0383dbcac4e

**Comment by axiom41** [comment]
Hi @Gloria323.
I had a look at your "my_issue.mp4" video and something is not clear to me with your steps.
Fierst of all, look at your system time: it's 14:39 when you started the video recording.
You first opened file c:\suiteA\suiteA1.robot in RIDE. This suite contains 7 Test Cases:

- just one
- CASE1
- sleep
- CASe2
- case3
- suiteA1
- suiteA2

Then you moved to VS Code already open and directly showing the same suiteA1.robot file (the file opening in VS Code is missing), but without Test Case named "sleep", and added Test Case "suiteA3"; the file in VS code is then showing (i noticed 1 less space in indentation of Keyword for CASE1):

- just one
- CASE1
- CASe2
- case3
- suiteA1
- suiteA2
- suiteA3

At this point, i couldn't notice the saving of the file in VS Code (probably you pressed Ctrl-S).

Then you returned to RIDE, showing the dialog with file change message and pressed "Yes". RIDE did not directly refresh the file and returned to "Div-auth-invite.robot" Test Suite (and this is the issue i described for my case), so you then manually selcted "File -> Open Test Suite (Ctrl-O)", but this time you opened ANOTHER Test Suite, i.e. c:\suiteA\suiteA.robot, that is obviously unchanged and different from c:\suiteA\suiteA1.robot you started from.
Please notice here: suiteA1.robot, that is the one you just changed in VS Code), has 14:39 as a modification time, that looks consistent, while the file you're selecting was modifies at 14:28

c:\suiteA\suiteA.robot in RIDE looks like a copy of c:\suiteA\suiteA1.robot, since it contains the same "initial" Test Cases.

Then you switched again to VS code and went to the already open "suiteA.robot" tab, where the file looks even different (did you reloaded/refreshed it?), containing only the 4 Test Cases:

- just one
- CASE1
- CASe2
- suiteA

and you added "suiteA5" at the end, saved in VS code (probably with Ctrl-S again) and returned to RIDE, that shows the dialog again. Here you clicked on "Yes" again and "Div-auth-invite.robot" was reloaded.

So why you operated on suiteA1.robot first and then on suiteA.robot that are different files?
I think you should only work with a single file at a time and ensure all tabs in VS Code are refreshed when you start working in that editor.
As a final tip, i can suggest you to install an extension to VS Code named "Robot Code" which adds useful fuctions to VS Code when editing Robot Framework files (e.g. syntax highlighting)

**Comment by Gloria323** [comment]
Hi @axiom41 ,
 1. Yes, I pressed Ctrl-S to save the suite change in vs code.
 2. I edit the suiteA and suiteA1 just want to say that I can 100% reproduce this issue.

**Comment by axiom41** [comment]
> May I ask what software you used to record your screen? Your screen recording is very clear, while mine is quite blurry.(_^▽^_)

I use the video recording feature of Snagit (my favourite screen capture tool, license needed)




> 2\. I edit the suiteA and suiteA1 just want to say that I can 100% reproduce this issue.

So why not reopening suiteA1 (the one you first modified in VS Code) in RIDE, to check that changes in VS Code were actually saved? From your video and last explanation, the issue you're experiencing looks (basically) like mine, i.e. after any modification in any external editor, RIDE asks to reload the suite/workspace but a previous one (in your case "Div-auth-invite.robot") is reloaded instead. I "extended" this, showing also that the issue is also occurring when trying to open other workpaces in RIDE, even without any change in suites done in external editors.

**Comment by JFoederer** [comment]
Good point @Gloria323 , even though the effect is similar they are not necessarily the same issue. I reopened RIDE today with the minimal test suites I tested with yesterday to try the other scenario as well.

To my surprise the following happened. Opening RIDE went fine, it just opened the most recent suite. Then I selected another suite from the history and instantly the dialog appeared. After selecting *Yes* it reverted back to the old suite. **So it does reproduce with even the smallest test suites** that have just a single robot file without further dependencies.

**Comment by HelioGuilherme66** [comment]
Well, I did reproduced the problem on my first attempt.
The file system monitoring function has some differences in Windows from the other Posix systems. It only considers directories monitoring. So when we want to test this function we must always open directories not single files.

I will look into this issue (and other related with the same function) with top priority.
(for start, we should never be asked about changes in project when we decided to open a different one. this is a long standing bug, which is causing a lot of problems, like you report now.)

**Comment by Gloria323** [comment]
Hi @HelioGuilherme66 ,
   I have updated to the latest version, and the issue has been resolved. It's much more comfortable to use now. Thank you so much！(*￣︶￣)

**Comment by JFoederer** [comment]
That is indeed much better. I do still get the _files changed_ pop-up in scenarios 1 and 2, but it then reloads the newly selected folder instead of the initial one. That is already a huge improvement.

**Comment by JFoederer** [comment]
While testing the latest version I encountered this other one on the file watcher:
![image](https://github.com/robotframework/RIDE/assets/32476108/a5d7ace7-c266-4b2d-b48b-d97ebd588f42)

This is when opening a test suite folder in Windows from a folder on my local Linux Ubuntu installation. Probably an edge case, so I wouldn't worry about it too much, but still wanted to share. It is rather annoying though, because the error pops up every time RIDE looses focus. No entries in the RIDE log.

**Comment by HelioGuilherme66** [comment]
@JFoederer I will catch the error and ignore file changes monitoring in that case.
May I suggest for you to map a drive letter to the share, and use it instead. It may work.
