### ISSUE TITLE
Blank squares left behind after a test run

### ISSUE THREAD

**Issue by JFoederer** [robotframework/RIDE#2741]
Some robot icons are being cleared in the tree view when running tests and the blank square is then persisted at its latest spot. There is at most one blank square added per test run. It is unclear what triggers this behaviour, it does not always happen.

The position of the blank squares is fixed with respect to the tree view window. This means that if you scroll inside the tree view, the blank squares scroll along. If you expand/collapse a test suite, then the blank square stays at its spot and is no longer with the test case it originated at.

![image](https://github.com/robotframework/RIDE/assets/32476108/f558f9b2-5f99-4046-9158-9bc426b3b373)

**Comment by JFoederer** [comment]
This was running RIDE 2.1dev23 on Windows with Python 3.11 and wxpython 4.2.1
I haven't noticed it on Linux yet.

**Comment by HelioGuilherme66** [comment]
@JFoederer This is very unusual, and I doubt it has anything to deal with RIDE code. Maybe the problem is with wxPython. Do you think the processing resources are low when that happens?

**Comment by JFoederer** [comment]
Yes, it is unusual, but no, it was not at all heavy on the resources. If anything, it is the opposite. This was a test suite with very few dependencies. It runs 94 test cases in less than half a second.

**Comment by JFoederer** [comment]
Having observed this issue for some time now, I do believe it only happens in very quick test runs where there is very little time to update the icons.

**Comment by JFoederer** [comment]
I have some new info on this issue. I witnessed it happening in real-time, followed by a RIDE crash.

- Consider a test suite consisting of 4 test cases,
- running very fast, taking just milliseconds to complete
- Updating the UI is a bit slower before the crash and I observe:
  - The first two tests are marked done with the green icon
  - The third test shows the lighter square, as shown in the initial issue description
  - From the fourth test the icon is removed altogether
  - RIDE freezes for a moment, than crashes

```
C:\Users\the_user\GitHub\robotframeworkMBT>C:\Users\the_user\AppData\Local\Programs\Python\Python312\python.exe -c "from robotide import main;main()"
DEBUG: project.py Project load_data robot version = b'7.2'
Traceback (most recent call last):
  File "C:\Users\the_user\AppData\Local\Programs\Python\Python312\Lib\site-packages\wx\core.py", line 3427, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\the_user\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\ui\treeplugin.py", line 435, in _set_icon_from_execution_results
    self._animctrl.Play()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Play'
Traceback (most recent call last):
  File "C:\Users\the_user\AppData\Local\Programs\Python\Python312\Lib\site-packages\wx\core.py", line 3427, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\the_user\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\ui\treeplugin.py", line 435, in _set_icon_from_execution_results
    self._animctrl.Play()
RuntimeError: wrapped C/C++ object of type AnimationCtrl has been deleted
Traceback (most recent call last):
  File "C:\Users\the_user\AppData\Local\Programs\Python\Python312\Lib\site-packages\wx\core.py", line 3427, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\the_user\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\ui\treeplugin.py", line 434, in _set_icon_from_execution_results
    self.SetItemWindow(node, self._animctrl, False)
  File "C:\Users\the_user\AppData\Local\Programs\Python\Python312\Lib\site-packages\wx\lib\agw\customtreectrl.py", line 4445, in SetItemWindow
    item.SetWindow(wnd, on_the_right)
  File "C:\Users\the_user\AppData\Local\Programs\Python\Python312\Lib\site-packages\wx\lib\agw\customtreectrl.py", line 2041, in SetWindow
    self._wnd.Enable(self._enabled)
RuntimeError: wrapped C/C++ object of type AnimationCtrl has been deleted
```

_RIDE v2.2dev23 running on Python 3.12.0 using wxPython 4.2.2_

**Comment by JFoederer** [comment]
Reproduced a second time with the exact same bahviour. Executing repeated runs and after some time the top icon turns blank, then a number of runs later the second and on to the third. When the last icon is hit: crash!

![Image](https://github.com/user-attachments/assets/5f6a1b74-eba2-4f97-9166-744e7b7972ff)
The last green was from the previous run, then it crashed.

**Comment by JFoederer** [comment]
Yes, this is a suite from an open source library I was working on. Load this folder into RIDE: https://github.com/JFoederer/robotframeworkMBT/tree/main/atest/robotMBT%20tests

The example was from this specific test suite, but it does not seem test suite specific.
https://github.com/JFoederer/robotframeworkMBT/blob/main/atest/robotMBT%20tests/05__repeating_scenarios/07__repetition_with_refinement.robot

It appears to be related to the animated robot icon during very fast execution. If the tree view is collapsed, the crash does not happen.

**Comment by JFoederer** [comment]
The Python installer came from python,org. I don't recall choosing anything custom during the install.

**Comment by JFoederer** [comment]
Ok, in realising that this project does not have the most straight forward test suites I tried to reproduce the issue on some of the more basic test suites. Just to keep things simple.

But so far it seems that the '_simple_' suites do not show the issues. But, as soon as a test suite is included that executes a test that is not present in the tree view, the issue pops up. Yes, it is possible to generate new test cases at runtime.

**Comment by HelioGuilherme66** [comment]
@JFoederer I fixed the important part of the issue. Now it should not crash. I did reproduced the white squares (and also missing execution state icons) in the execution of the test suite from https://github.com/JFoederer/robotframeworkMBT

Because this is a corner case, I am inclined to mark this issue as `fixed` (no crash), and document that these blank squares may appear in certain executions.

Tested with RIDE v2.2dev29 in Windows 10 with Python 3.12, wxPython 4.2.3 and RF 7.2.2.

**Comment by JFoederer** [comment]
I am sorry to say the issue still occurs, @HelioGuilherme66. I am running RIDE v2.2dev29 on Windows 11 with Python 3.13.1, wxPython 4.2.3 and RF 7.2.2.

**Comment by JFoederer** [comment]
Yes indeed. Just like before. Blank squares followed by a crash. Although the crash can even occur when the suite is folded in from the tree view and the icons don't show.

**Comment by HelioGuilherme66** [comment]
@JFoederer Please try again with 2.2dev34
(On Linux Fedora 42, KDE Plasma 6, Python 3.13, wxPython 4.2.4a15946+920a2bde, did not have crashes and icons changed colors)

**Comment by JFoederer** [comment]
Where can I find that wxPython version?

**Comment by HelioGuilherme66** [comment]
@JFoederer A year has passed, so let's look a this again ;):
I used Python 3.14.5 in a virtual env, with wxPython 4.2.5, Robot Framework 7.4.2 and RIDE development version, 2.2.5.dev2, on Fedora Linux 42.
I can see the Run Status bar only start changing after some seconds, and the Tree icons were starting already to be updated.
In the below screen capture (GUI in Portuguese), we can see Skipped tests in the end of execution, and the total in Robot Framework output window, being much different from Run Status bar, which have zero skipped tests. Some tests did not run.

<img width="1562" height="779" alt="Image" src="https://github.com/user-attachments/assets/8547be98-e9ad-4f3c-83ed-c3da9966ba64" />

On other run, with the test suites with tests not ran, and with Skipped tests, we can see it took one second, and Run Status bar did not updated the counters. The values reported by Robot Framework match the 17 Skipped tests identified in the Tree, but not the run and passed, 7 in Console, and 6 colored green in Tree.

<img width="1562" height="779" alt="Image" src="https://github.com/user-attachments/assets/1771276b-775c-4206-b185-cb484c9fc058" />

I don't what I can do about this issue (the crash should not happen), or do you have any suggestion?

**Comment by JFoederer** [comment]
Hi @HelioGuilherme66, and thank you for getting back to this one. The issue is still there and crashes, of course, are always annoying. Any Suggestions, you ask? Not for the root cause, but I can clarify a few aspects.

For instance, The skipped test cases you get are due to missing optional dependencies. This can be remedied by running the full installation: `pip install --upgrade robotframework-mbt[full]`. This is however **not essential** for reproducing the issue. Also non-essential are a some of the other test cases that remain unexecuted. Like the 'impossible scenario', it is explicitly checked that an error is generated when there is an unreachable scenario. Causing intended failures to be converted into pass result.

For reproducing the issue you do need these special situations. But, mind you, due to the model-based nature of these suites, there are still plenty of non-standard situations that could add to the issue.

As an example I could quite easily (although not 100%) **reproduce the issue running the single test suite** for paired repetition (`RobotMBT tests.Scenario linking.Repeating scenarios.Paired repetition`):
<img width="534" height="352" alt="Image" src="https://github.com/user-attachments/assets/567b812e-b1d5-47d3-bc75-df783f663173" />

This test suite contains 5 scenarios, but when executed it runs 7 scenarios. The 'paired repetition' refers to the fact that **two of the scenarios** need to be **repeated** in tandem, before the final scenario can be reached.

<img width="967" height="1203" alt="Image" src="https://github.com/user-attachments/assets/2f7e3d38-a6d1-4434-99fe-5ebd8e718006" />

You probably do need to know all the in and outs on why this is needed. See the documentation here if you are interested: [RobotMBT](https://github.com/JFoederer/robotframeworkMBT). The important thing I want to point out, is that there are more scenarios executed, than are originally in the test suite.

How does RIDE decide which test is being executed? As you can see in the image, repeated scenarios do not get the same name. Repetitions get (rep **n**) added to their name. We previously found out that the crashes are related to updating the icons in the tree. Are there maybe too many assumptions on which test cases will be in the final test suite?
